"""
Milestone 3 — Analytics Database Models

New tables for the Adaptive Intelligence, Analytics & Dashboard features:
  • BehaviorAnalytics  — daily behavioural metrics per user
  • HabitScore         — daily weighted habit score per user
  • Recommendation     — personalized rule-based recommendations
  • DifficultyHistory  — log of adaptive difficulty transitions
  • UserStatistics     — rolling 30-day aggregate statistics
"""

import uuid
from datetime import UTC, datetime
from typing import TYPE_CHECKING

from sqlalchemy import (
    Boolean,
    Date,
    DateTime,
    Float,
    ForeignKey,
    Integer,
    String,
    Text,
)
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.database.base import Base

if TYPE_CHECKING:
    from app.models.user import User


class BehaviorAnalytics(Base):
    """Stores daily computed behavioural analytics for a user."""
    __tablename__ = "behavior_analytics"
    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    user_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True)
    analytics_date: Mapped[datetime] = mapped_column(Date, nullable=False)
    wake_up_consistency: Mapped[float] = mapped_column(Float, default=0.0)
    avg_wake_up_delay_minutes: Mapped[float] = mapped_column(Float, default=0.0)
    avg_snooze_count: Mapped[float] = mapped_column(Float, default=0.0)
    sleep_schedule_adherence: Mapped[float] = mapped_column(Float, default=0.0)
    challenge_success_rate: Mapped[float] = mapped_column(Float, default=0.0)
    daily_productivity_score: Mapped[float] = mapped_column(Float, default=0.0)
    avg_sleep_duration_hours: Mapped[float] = mapped_column(Float, default=0.0)
    total_snooze_count: Mapped[int] = mapped_column(Integer, default=0)
    total_challenges_attempted: Mapped[int] = mapped_column(Integer, default=0)
    total_challenges_successful: Mapped[int] = mapped_column(Integer, default=0)
    avg_challenge_completion_time: Mapped[float] = mapped_column(Float, default=0.0)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=lambda: datetime.now(UTC))
    updated_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=lambda: datetime.now(UTC), onupdate=lambda: datetime.now(UTC))
    user: Mapped["User"] = relationship("User", back_populates="behavior_analytics")


class HabitScoreRecord(Base):
    """Stores the daily calculated habit score using the weighted formula."""
    __tablename__ = "habit_scores"
    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    user_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True)
    score_date: Mapped[datetime] = mapped_column(Date, nullable=False)
    total_score: Mapped[float] = mapped_column(Float, default=0.0)
    wake_up_consistency_raw: Mapped[float] = mapped_column(Float, default=0.0)
    challenge_success_raw: Mapped[float] = mapped_column(Float, default=0.0)
    snooze_reduction_raw: Mapped[float] = mapped_column(Float, default=0.0)
    sleep_adherence_raw: Mapped[float] = mapped_column(Float, default=0.0)
    wake_up_consistency_weighted: Mapped[float] = mapped_column(Float, default=0.0)
    challenge_success_weighted: Mapped[float] = mapped_column(Float, default=0.0)
    snooze_reduction_weighted: Mapped[float] = mapped_column(Float, default=0.0)
    sleep_adherence_weighted: Mapped[float] = mapped_column(Float, default=0.0)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=lambda: datetime.now(UTC))
    user: Mapped["User"] = relationship("User", back_populates="habit_scores")


class Recommendation(Base):
    """Stores personalised recommendations generated by the rule engine."""
    __tablename__ = "recommendations"
    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    user_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True)
    title: Mapped[str] = mapped_column(String(255), nullable=False)
    description: Mapped[str] = mapped_column(Text, nullable=False)
    category: Mapped[str] = mapped_column(String(50), nullable=False)
    priority: Mapped[str] = mapped_column(String(20), default="medium")
    rule_id: Mapped[str] = mapped_column(String(100), nullable=False)
    is_active: Mapped[bool] = mapped_column(Boolean, default=True)
    is_dismissed: Mapped[bool] = mapped_column(Boolean, default=False)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=lambda: datetime.now(UTC))
    expires_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True), nullable=True)
    user: Mapped["User"] = relationship("User", back_populates="recommendations")


class DifficultyHistory(Base):
    """Logs each adaptive difficulty level change for a user."""
    __tablename__ = "difficulty_history"
    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    user_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), ForeignKey("users.id", ondelete="CASCADE"), nullable=False, index=True)
    previous_difficulty: Mapped[str | None] = mapped_column(String(20), nullable=True)
    new_difficulty: Mapped[str] = mapped_column(String(20), nullable=False)
    accuracy_at_change: Mapped[float] = mapped_column(Float, default=0.0)
    avg_completion_time: Mapped[float] = mapped_column(Float, default=0.0)
    snooze_count_at_change: Mapped[int] = mapped_column(Integer, default=0)
    reason: Mapped[str] = mapped_column(String(255), nullable=True)
    changed_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=lambda: datetime.now(UTC))
    user: Mapped["User"] = relationship("User", back_populates="difficulty_history")


class UserStatistics(Base):
    """Aggregated rolling statistics computed over the previous 30 days."""
    __tablename__ = "user_statistics"
    id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
    user_id: Mapped[uuid.UUID] = mapped_column(UUID(as_uuid=True), ForeignKey("users.id", ondelete="CASCADE"), nullable=False, unique=True, index=True)
    current_difficulty: Mapped[str] = mapped_column(String(20), default="beginner")
    total_alarms_set: Mapped[int] = mapped_column(Integer, default=0)
    total_alarms_dismissed: Mapped[int] = mapped_column(Integer, default=0)
    total_snoozes: Mapped[int] = mapped_column(Integer, default=0)
    total_challenges_attempted: Mapped[int] = mapped_column(Integer, default=0)
    total_challenges_passed: Mapped[int] = mapped_column(Integer, default=0)
    avg_wake_up_delay_minutes: Mapped[float] = mapped_column(Float, default=0.0)
    avg_snooze_count: Mapped[float] = mapped_column(Float, default=0.0)
    avg_challenge_time_seconds: Mapped[float] = mapped_column(Float, default=0.0)
    avg_sleep_duration_hours: Mapped[float] = mapped_column(Float, default=0.0)
    wake_up_consistency_pct: Mapped[float] = mapped_column(Float, default=0.0)
    challenge_accuracy_pct: Mapped[float] = mapped_column(Float, default=0.0)
    sleep_adherence_pct: Mapped[float] = mapped_column(Float, default=0.0)
    current_wake_streak: Mapped[int] = mapped_column(Integer, default=0)
    best_wake_streak: Mapped[int] = mapped_column(Integer, default=0)
    latest_habit_score: Mapped[float] = mapped_column(Float, default=0.0)
    computed_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=lambda: datetime.now(UTC))
    updated_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), default=lambda: datetime.now(UTC), onupdate=lambda: datetime.now(UTC))
    user: Mapped["User"] = relationship("User", back_populates="user_statistics")
