// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDICcbpsDCFfyM6dvYI2JKJQB_Dnu_Tj_4',
    appId: '1:998211722827:web:2a5ffef5c61299ced777ce',
    messagingSenderId: '998211722827',
    projectId: 'cognitive-alarm-platform',
    authDomain: 'cognitive-alarm-platform.firebaseapp.com',
    storageBucket: 'cognitive-alarm-platform.firebasestorage.app',
    measurementId: 'G-YTZNR4EJBE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZrwGZ-TiMzXFfJhT2oZAVKJbdpz9YW9k',
    appId: '1:998211722827:android:c3f3a4190ac85e8ad777ce',
    messagingSenderId: '998211722827',
    projectId: 'cognitive-alarm-platform',
    storageBucket: 'cognitive-alarm-platform.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkkiwbvSRd3HqVVd5bXjNeKGSstjlx2yE',
    appId: '1:998211722827:ios:2b8c4535371979a8d777ce',
    messagingSenderId: '998211722827',
    projectId: 'cognitive-alarm-platform',
    storageBucket: 'cognitive-alarm-platform.firebasestorage.app',
    androidClientId: '998211722827-b9qbvq8499maldj7qth8rafrimpul3bq.apps.googleusercontent.com',
    iosClientId: '998211722827-79r0hh6itcs6rmgdjitsers8kb9ce6is.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartAlarmSystem',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkkiwbvSRd3HqVVd5bXjNeKGSstjlx2yE',
    appId: '1:998211722827:ios:2b8c4535371979a8d777ce',
    messagingSenderId: '998211722827',
    projectId: 'cognitive-alarm-platform',
    storageBucket: 'cognitive-alarm-platform.firebasestorage.app',
    androidClientId: '998211722827-b9qbvq8499maldj7qth8rafrimpul3bq.apps.googleusercontent.com',
    iosClientId: '998211722827-79r0hh6itcs6rmgdjitsers8kb9ce6is.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartAlarmSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDICcbpsDCFfyM6dvYI2JKJQB_Dnu_Tj_4',
    appId: '1:998211722827:web:abecbfb74698d751d777ce',
    messagingSenderId: '998211722827',
    projectId: 'cognitive-alarm-platform',
    authDomain: 'cognitive-alarm-platform.firebaseapp.com',
    storageBucket: 'cognitive-alarm-platform.firebasestorage.app',
    measurementId: 'G-Y7Q0WTQ30B',
  );
}
