from app.routers import (
    adaptive_difficulty,
    admin,
    alarms,
    analytics,
    auth,
    behavioral_analytics,
    challenges,
    coaches,
    habits,
    health,
    notifications,
    recommendations,
    users,
)

__all__ = [
    "adaptive_difficulty",
    "admin",
    "alarms",
    "analytics",
    "auth",
    "behavioral_analytics",
    "challenges",
    "coaches",
    "habits",
    "health",
    "notifications",
    "recommendations",
    "users",
]
